visa service process for the node
org-zpr/zpr-core pull request #158
Opened 2024-07-04 21:15 UTC by mkolehmainen

I am opening this PR for some early comments. This is _not_ ready to be merged -- for one thing there are no unit tests.

2024-07-05 21:43 UTC, cpacejo requested changes
Still have some files to review, checkpointing my comments for now…

2024-07-05 21:43 UTC, cpacejo commented on node/src/vsapi/mod.rs
> +// Autogenerated by Thrift Compiler (0.20.0)
I would advise we do not check in generated files.  Let's always generate them as part of the build process.

Actually… where is the source for this?  Is it already checked in?

2024-07-05 21:43 UTC, cpacejo commented on visaservice/thrift/Makefile
>  install-rs: rs
Should be mentioned in .PHONY?

2024-07-05 21:43 UTC, cpacejo commented on node/src/vs/vsconn.rs
> +const POLL_INTERVAL_MS: u64 = 5000;
Maybe use a [`Duration`](https://doc.rust-lang.org/std/time/struct.Duration.html) here?

2024-07-05 21:43 UTC, cpacejo commented on node/src/config.rs
> +        return cert_pb.to_str().unwrap().to_string();
I think you can return a `PathBuf` here, or `Box<Path>`.

2024-07-05 21:43 UTC, cpacejo commented on node/src/config.rs
> +        match self.claims.get(key) {
Can be written also as `Some(self.claims.get(key)?.as_str()?.to_string())`

2024-07-05 21:43 UTC, cpacejo commented on node/src/config.rs
> +            hmap.insert(k.to_string(), v.to_string());
`to_string()` is part of the `Display` mechanism: https://doc.rust-lang.org/std/string/trait.ToString.html#tymethod.to_string  My understanding is it's intended for user-facing display.  I think `String::from(...)` is what we want here.

(Same comment for the other occurrences in this file…)

2024-07-05 21:43 UTC, cpacejo commented on node/src/config.rs
> +            *a // somehow this de-ref returns a copy of the addr ???? XXX
`a` here is a reference, since you're matching against a reference (`&self.node_addr`).  So the `*` is needed to dereference that (which then results in a copy being made to return it).  I would expect you could drop both the `&` and `*` and things should work.

2024-07-05 21:43 UTC, cpacejo commented on node/src/config.rs
> +pub fn load_configuration(path: &str) -> Result<Configuration, std::io::Error> {
`Path` instead of `&str`?

2024-07-05 21:43 UTC, cpacejo commented on node/src/config.rs
> +    let mut reader = std::io::BufReader::new(file);
I think `File` directly implements `read_to_string()`, which is already reading in large chunks, so the `BufReader` I think is unnecessary.

2024-07-05 21:43 UTC, cpacejo commented on node/src/config.rs
> +    base_path: String,
Store these as `PathBuf`s instead maybe?

2024-07-05 23:21 UTC, mkolehmainen commented on visaservice/thrift/Makefile
>  install-rs: rs
y

2024-07-05 23:25 UTC, mkolehmainen commented on node/src/config.rs
> +            *a // somehow this de-ref returns a copy of the addr ???? XXX
yes thanks

2024-07-05 23:26 UTC, mkolehmainen commented on node/src/vsapi/mod.rs
> +// Autogenerated by Thrift Compiler (0.20.0)
Eh... I don't want to require the thrift build chain in order to build the project.  These files should change very infrequently (once we get to a certain point...).

2024-07-15 15:17 UTC, mkolehmainen commented on node/src/vsapi/mod.rs
> +// Autogenerated by Thrift Compiler (0.20.0)
I have created an issue org-zpr/zpr-core#196 for our new "manifest" idea.

2024-07-15 17:02 UTC, closed without merging