165 implement capture worker state
org-zpr/zpr-core pull request #169
Opened 2024-07-09 17:17 UTC by owenrhysthomas

2024-07-09 20:25 UTC, owenrhysthomas commented
~~We need to install libpcap-dev on GitHub, that's the reason that the PH runner can't compile the code and it won't link.~~ Done

2024-07-10 19:20 UTC, cpacejo requested changes
Just a couple changes in the capture file API (specifically there's a way we can do closing without consuming the entire mutex).

2024-07-10 19:20 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +#[allow(dead_code)]
Since these are referenced in the assembly probably the `dead_code` annotations are no longer necessary?

2024-07-10 19:20 UTC, cpacejo commented on .github/workflows/rust-adapter.yml
> +      run: sudo apt update && sudo apt install libpcap-dev && cd adapter/ph && make build && make test
Ah nice good catch!

2024-07-10 19:20 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +                capture: pcap::Capture::dead(pcap::Linktype(0)).unwrap(), // not sure what Linktype this should be
We will need to register our own! :)  But for now, use `USER0`.

2024-07-10 19:20 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +    pub fn destroy_savefile(self) {
I think just setting `self.savefile = None` should do the trick here (and thus you can use `&mut self`).  That will cause the savefile's drop method to be executed automatically.  (Note that we're implicitly relying on this behavior in `open_capture_file` as well, if a capture file is already open.)

If you did want to explicitly call drop I think you can do `self.savefile.take().map(drop)`.  (`take()` moves the item out of the option.)  I don't think that's necessary though.

Aside – I'd use the term "close" rather than "destroy"; "destroy" to me sounds like the underlying file might be deleted.

2024-07-10 19:20 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +    pub fn flush_savefile(&mut self) -> Result<(), pcap::Error> {
Let's use `capture_file` instead of `savefile` for all three of these to keep them consistent.

2024-07-10 19:20 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +    pub fn open_capture_file(&mut self, path: String) {
Let's accept a [`Path`](https://doc.rust-lang.org/nightly/std/path/struct.Path.html) here instead of a `String`.

2024-07-10 19:21 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +        self.inner_cap.get_mut().savefile =
Ah, yes, here you will want to use `.lock().await`, not `.get_mut()`.  Then, all these methods can accept `&self` instead of `&mut self`.

2024-07-10 19:46 UTC, owenrhysthomas commented on adapter/ph/src/capture_worker.rs
> +    pub fn destroy_savefile(self) {
~~I changed the way I do these methods (I had to make them async so I could use the combination of .lock().await to access the object in the Mutex instead of .get_mut(), so I'll make this change in issue https://github.com/org-zpr/zpr-core/issues/166 (PR https://github.com/org-zpr/zpr-core/pull/180)~~ Never mind, I will just apply the changes in this PR

2024-07-11 13:29 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +        self.inner_cap.lock().await.savefile =
You'll want to just take the lock once here.  E.g.:
```
let inner_cap = self.inner_cap.lock().await;
inner_cap.savefile = inner_cap.capture.savefile(path).unwrap();
```

2024-07-11 13:32 UTC, cpacejo requested changes

2024-07-11 13:32 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +            .unwrap()
Rather than `unwrap()` here, let's simply return success if there's no active savefile.

2024-07-11 13:53 UTC, cpacejo approved these changes
Perfect thanks!

2024-07-11 14:11 UTC, merged