166 blocked implement capture worker
org-zpr/zpr-core pull request #180
Opened 2024-07-10 14:43 UTC by owenrhysthomas

2024-07-10 19:37 UTC, cpacejo requested changes
Just needs a change in the logic to check for an active savefile – my description is probably not very clear so we can chat if you have questions :)  Otherwise looks good!

2024-07-10 19:37 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +    path: String,
The capture path we'll be setting via an RPC call, no need to accept it as an argument here.

2024-07-10 19:37 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +        for cap_pack in &messages {
Right here (inside the `while`, outside the `for`) you'll want to grab the mutex of `inner_cap`, and while holding it, check whether the savefile exists (since concurrently, the RPC worker can open and close the savefile), i.e. with a `match`.  Then, inside the `for`, loop through and write everything to the savefile you found.  (Or, if there was no savefile, just skip the `for` entirely.)

(For reference – you can write `let lock = foo.lock().await;` to grab and hold the mutex for the rest of the lexical code block.)

(The idea being to only grab the mutex once for each batch of packets, rather than once for every packet.)

2024-07-10 19:37 UTC, cpacejo commented on adapter/ph/src/queues.rs
> +impl<'pktbuf> CapPacket<'pktbuf> {
I think public members like you have above is fine – so this `impl` block can be safely deleted.

2024-07-10 20:59 UTC, owenrhysthomas commented on adapter/ph/src/capture_worker.rs
> +        for cap_pack in &messages {
Got it. I was originally going to use a match, but I wasn't sure if calling `open_capture_file` inside the `while` would cause problems because it's repeatedly opening the file.

2024-07-11 13:37 UTC, cpacejo requested changes

2024-07-11 13:37 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +                    asm.capture_worker.open_capture_file(&path).await;
The RPC worker will be opening and closing the file.  So here you'll just want to write to it.

2024-07-11 13:37 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +        caplen: cap_pack.packet.body().len() as u32, // not sure if this is the right value, perhaps should be cap_pack.packet.metadata().len
This is correct!  (`caplen` is how much we are recording to the capture file, which we are recording the full packet body, so it's equal to `len`.)

2024-07-11 13:37 UTC, cpacejo commented on adapter/ph/src/flow_control.rs
> +    pub(crate) fn new(inbound: bool, outbound: bool) -> Self {
I would just initialize these both to false, no need to accept as parameters here.

2024-07-11 13:57 UTC, cpacejo approved these changes
Looks good!  One nit but feel free to commit as-is.

2024-07-11 13:57 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
> +            match &mut locked_mutex.savefile {
Not a bug, but you can hoist this out of the for loop (i.e., just perform the `match` once, and then either loop or don't).  It won't be changing out from under you because you are holding the lock.  (Feel free to change this in a later PR.)

2024-07-11 14:01 UTC, owenrhysthomas commented on adapter/ph/src/capture_worker.rs
> +            match &mut locked_mutex.savefile {
This makes sense, I realized I misread your original comment about the match, I just fixed it, pushing right now.

2024-07-11 14:05 UTC, merged