171 blocked copy packets to capture queue
org-zpr/zpr-core pull request #182
Opened 2024-07-11 13:30 UTC by owenrhysthomas

2024-07-12 18:56 UTC, cpacejo requested changes
Looks good but I agree I would restructure those loops to be in terms of the packets to send, not the buffers we're copying them to.  I suspect it will simplify that code a bit.

2024-07-12 18:56 UTC, cpacejo commented on adapter/ph/src/capture_worker.rs
>  pub const USER0: i32 = 147;
I think I missed this in an earlier review – why not use `https://docs.rs/pcap/latest/pcap/struct.Linktype.html#associatedconstant.USER0` directly?

2024-07-12 18:56 UTC, cpacejo commented on adapter/ph/src/inbound_processor_worker.rs
> +                    // TODO potentially restrustructure, this wastes a buffer if there are lots of test packets
I think if you write the loop in terms of `pkts` instead, you should be able to `pop()` buffers off of `bufs`.  And then just pass the remaining `bufs` to `put_buffers()`.

2024-07-12 18:56 UTC, cpacejo commented on adapter/ph/src/inbound_processor_worker.rs
> +                                asm.buffer_stack.put_buffer(ret_buf);
Here, I would exit the loop also.  Subsequent enqueues are almost certain to fail.

Also let's count failed captures here as well.  (A separate PR is fine for this to avoid PR scope creep.)

2024-07-12 18:56 UTC, cpacejo commented on adapter/ph/src/main.rs
> +                    batch_size: capture_queue_size,
Like the other queues, let's configure this in terms of desired batch size instead of queue size, and make the queue size 2× the batch size.

2024-07-12 18:56 UTC, cpacejo commented on adapter/ph/src/queues.rs
> +                return Err(TryEnqueueError::Full(x));
(Also I must have missed this in an earlier review, sorry!)  Instead of returning a `CapPacket` message here (which is otherwise not exposed to the user of this API) let's pull out the packet from the message (i.e. `x.packet`) and return that.  (Also let's rename `x` to e.g. `cap_pack` to make it clearer to a reader what's going on here.)

2024-07-12 18:56 UTC, cpacejo commented on adapter/ph/src/queues.rs
> +// impl<'pktbuf> CapPacket<'pktbuf> {
`destroy()` shouldn't be needed here.  I think it's correct to treat the `CapPacket` message as a plain structure and just let the receiver destructure it and `destroy()` the contained packet directly.

2024-07-12 20:31 UTC, owenrhysthomas commented on adapter/ph/src/inbound_processor_worker.rs
> +                                asm.buffer_stack.put_buffer(ret_buf);
https://github.com/org-zpr/zpr-core/issues/192

2024-07-15 17:31 UTC, cpacejo approved these changes
Perfect thanks!!  I think can even get rid of the `num_bufs` counter in the capture loop but otherwise looks perfect.

2024-07-15 17:31 UTC, cpacejo commented on adapter/ph/src/inbound_processor_worker.rs
> +                    let pkt_clone: Packet = pkt.clone_into(bufs.pop().unwrap());
Instead of tracking `num_bufs` separately, you can just rely on the return value of `pop()` here (and break from the loop early too).  i.e. `match bufs.pop() { None => break, Some(buf) => ... }`

2024-07-15 17:31 UTC, cpacejo commented on adapter/ph/src/queues.rs
> +                // cap_pack.destroy();
This commented code I think can go?

2024-07-15 19:09 UTC, merged