242 decode type as name not just number
org-zpr/zpr-core pull request #243
Opened 2024-07-25 14:14 UTC by owenrhysthomas

2024-07-25 15:08 UTC, cpacejo requested changes

2024-07-25 15:08 UTC, cpacejo commented on tools/zdp_dissector.lua
> +    if type == 0 then type_name = "Transit Packet"
I feel this might slow down packet dissection to have linear lookup like this.  Let's use a table lookup like [this](https://stackoverflow.com/a/37493047) (but with strings instead of functions of course).  And if the packet type isn't found in the table, then fall back to a short if/elseif sequence to classify for the various reserved ranges.

2024-07-26 17:15 UTC, cpacejo approved these changes
Looks good but if possible let's lift the table definition outside the function.  Feel free to push after making that change!

2024-07-26 17:15 UTC, cpacejo commented on tools/zdp_dissector.lua
> +    local type_name_table =
I think by being defined inside the function body this table will get recreated on every function call (very expensive).  Is it possible to lift `type_name_table` outside the function?

(I know it's a little weird for me to be concerned about performance here especially without measurement – I'm just looking for easy wins now.  Opening a large PCAP in Wireshark can take a loooong time to dissect all the packets…)

2024-07-26 17:16 UTC, owenrhysthomas commented on tools/zdp_dissector.lua
> +    local type_name_table =
Totally makes sense, I'm on it now.

2024-07-26 17:43 UTC, merged