256 add report messages  handle in inbound processor worker
org-zpr/zpr-core pull request #260
Opened 2024-07-30 17:34 UTC by owenrhysthomas

2024-07-30 20:08 UTC, cpacejo requested changes

2024-07-30 20:08 UTC, cpacejo commented on adapter/ph/src/inbound_processor_worker.rs
> +                    pkt.advance(2);
Instead of `2`, use `std::mem::size_of::<ZdpReportHeader>()`.

2024-07-30 20:08 UTC, cpacejo commented on adapter/ph/src/inbound_processor_worker.rs
> +                // or something similar?
Specifically check that `report_data_len <= pkt.body().len()` after advancing past the ZdpReportHeader.  (Equals is too strict here – we just need to make sure we don't attempt to read past the end of the packet.)

But yes, if it doesn't validate, ignore it for now.  Actually let's also leave a TODO to revisit – Sarah & I were discussing this morning how best to handle protocol errors since we don't have a system in place yet.

2024-07-30 20:08 UTC, cpacejo commented on adapter/ph/src/inbound_processor_worker.rs
> +                    eprintln!("{}", std::str::from_utf8(pkt.body()).unwrap());
Here use `pkt.body()[..report_data_length]`, since the report may shorter than the remainder of the packet.  (Though, I wouldn't expect these to ever differ… I'm just going based off the spec here.)

(Note, to satisfy the borrow checker, you'll need to read `report_data_length` into a local variable before calling `advance()` above.)

2024-07-31 15:48 UTC, cpacejo approved these changes
Looks good!  Just a suggestion to clean up some redundant code around the message length check.  Also don't forget to replace the `2` in the call to `.advance()` with a call to `size_of()`.  Feel free to push after making that change!

2024-07-31 15:48 UTC, cpacejo commented on adapter/ph/src/inbound_processor_worker.rs
> +                    let report_data_length: usize = hdr.report_data_length.into();
No need for the 2nd `let report_data_length` here, the scope of the 1st one covers this block.

Also if you move the call to `advance` outside the `if` check it will become simpler (no need to subtract).

2024-07-31 16:00 UTC, owenrhysthomas commented on adapter/ph/src/inbound_processor_worker.rs
> +                    let report_data_length: usize = hdr.report_data_length.into();
Yes! I forgot to delete the one inside. I moved it out to streamline and then forgot to remove it inside :sweat_smile:

2024-07-31 16:12 UTC, merged