addition of ancillary data
org-zpr/zpr-core pull request #312
Opened 2024-08-12 13:32 UTC by owenrhysthomas

2024-08-13 18:41 UTC, owenrhysthomas commented on adapter/ph/src/rpc_worker.rs
> +                let mut buf = [0; 8];
could use const here instead of `8`

2024-08-13 18:42 UTC, owenrhysthomas commented on adapter/ph/src/rpc_worker.rs
> +                let file = unsafe { File::from_raw_fd(fd) };
should have comment with justification of safety for this unsafe operation, but I'm not sure what that justification is.

2024-08-13 19:07 UTC, owenrhysthomas commented on adapter/ph-debug/src/main.rs
> +    let borrowed_fd = unsafe { BorrowedFd::borrow_raw(file_descriptor) };
also need justification for use of unsafe here

2024-08-14 14:13 UTC, cpacejo commented on adapter/ph/src/rpc_worker.rs
> +                let file = unsafe { File::from_raw_fd(fd) };
(Aside – with my latest changes to the ancillary data stuff, you can do `File::from(fd.try_into_owned())` to do this safely!)

As written above though – and generally – to write a good safety justification, you can base it on the safety requirement of the function you're calling.  So for [`from_raw_fd()`](https://doc.rust-lang.org/nightly/std/os/fd/trait.FromRawFd.html#tymethod.from_raw_fd), the requirement is:

> The fd passed in must be an [owned file descriptor](https://doc.rust-lang.org/nightly/std/io/index.html#io-safety); in particular, it must be open.

So a correct safety comment could be something like:

```
// SAFETY: Any FD received in ancillary data is owned by us and open.
```

2024-08-14 14:48 UTC, cpacejo requested changes
Nice looks good!  Just requesting a couple changes to make to make use of the new API changes I made so you can avoid `unsafe`.  (I can explain the "Cow" stuff in person/over Slack too.)

Also I'm realizing how glad I am to have this functionality!  I am reminded of past products I've worked on that _didn't_ have this functionality and how anxious I and others would get using a debug tool in production, that we might accidentally overwrite some critical system file when asking the main process to log something somewhere…

2024-08-14 14:48 UTC, cpacejo commented on adapter/ph-debug/src/main.rs
> +    let borrowed_fd = unsafe { BorrowedFd::borrow_raw(file_descriptor) };
You can use [`.as_fd()`](https://doc.rust-lang.org/std/fs/struct.File.html#impl-AsFd-for-File) to go directly from a `File` to a `BorrowedFd` safely.  (And then, with my new API, `.from()` or `CowFd::into()` to go from a `BorrowedFd` into a `CowFd`.)

2024-08-14 14:48 UTC, cpacejo commented on adapter/ph-debug/src/main.rs
> +        .read(true)
Read permission shouldn't be necessary I think.

2024-08-14 14:48 UTC, cpacejo commented on adapter/ph-debug/src/main.rs
> +    let buf = [1; 8];
I think this can even just be a single byte (`[1; 1]`) – no need to define a constant in that case.  Though I'd add a comment stating _why_ we need this (i.e. because you need to send some real data with ancillary data).

2024-08-14 14:48 UTC, cpacejo commented on adapter/ph/src/rpc_worker.rs
> +                let file = unsafe { File::from_raw_fd(fd.as_raw_fd()) };
So now with `into_messages()`, you should be able to call `fd.try_into_owned()?` to get an `OwnedFd` without needing `unsafe`.  (Better than the proposed standard! :) )

2024-08-14 14:48 UTC, cpacejo commented on adapter/ph/src/rpc_worker.rs
> +                let mut buf = [0; 8];
Even just 1 byte I think is enough – and then no need for a const, just a comment that this is receiving the necessary byte you are sending on the other side.

2024-08-15 02:50 UTC, cpacejo approved these changes
Perfect thanks!!  Weird that Tokio File doesn't implement `From<OwnedFd>`, what you have is good tho!

2024-08-15 14:06 UTC, merged