Hook KM subsystem into the ph
org-zpr/zpr-core pull request #378
Opened 2024-08-29 17:58 UTC by mkolehmainen

While not actually hooked up per se, this has integrated the KM into the fastpath.   Facility is provided (with small example in main.rs) to add KM protocol to links when they come up and remove it when they go down.  New flags have been added to the binary that allow the KM to be turned off, and also allow for insecure use of ZPI=0.  Note that these flags allow the basic-test to run.

What this does-

- Refactor the KM so that the encry/decrypt stuff is just a codec interface created by the (eg) Noise state machine.
- New KM signal that tells you when an SA is established AND sends all state required to use it.
- Rework encrypt and decrypt in fastpath a bit.
- Some code in main and assembly to set up state for KM, and to illustrate how to add an adapter link.
- Two new "threads" that monitor the link key management machines: one to watch for signals and update assembly state, and one to watch for KM payloads and emit ZDP Key Management messages.
- I have kept the old node and cd code in sync for now.

2024-09-04 15:39 UTC, cpacejo commented on adapter/ph/src/assembly.rs
> +    pub fn new() -> Self {
You can instead `impl Default for PhFlags { fn default() -> Self { ... } }`.

2024-09-04 15:39 UTC, cpacejo commented on adapter/ph/src/assembly.rs
> +    pub sa_states: Arc<DashMap<zpr::LinkId, SAState>>,
Let's put the `SAState` into the `peer_table` -- that's the home for all link state.

2024-09-04 15:39 UTC, cpacejo commented on adapter/ph/src/main.rs
> +                sa_states: Arc::new(DashMap::new()),
No need for `Arc` here I don't think.  (Though see my other comment about leveraging `peer_state` to store this state.)

2024-09-04 15:39 UTC, cpacejo commented on adapter/ph/src/main.rs
> +            let km_loop_ctok = Box::leak(Box::new(km_mpx_ctok.clone()));
Instead of boxing this, you can move it into the `async` block, just write `async move { }` instead of `async { }`.

2024-09-04 15:39 UTC, cpacejo commented on adapter/ph/src/main.rs
> +                        }
What cancels this thread?

(Right now no other worker thread gets cancelled for any reason; the only way "out" is to terminate the process.  Link up/down let's have working independently of process start/stop.  I'm somewhat of the mind to _only_ have terminate-as-shutdown; every product I've worked on with a "clean" shutdown (a) had tons of teardown-synchronization bugs in the clean shutdown path, and (b) never actually relied on the clean shutdown path.)

2024-09-04 15:39 UTC, cpacejo commented on adapter/ph/src/main.rs
> +            });
Let's stick this worker thread in its own module like how the other worker threads are.

2024-09-04 19:22 UTC, mkolehmainen commented on adapter/ph/src/main.rs
> +                        }
Yeah, ok that's fine with me.  That KM thread in particular should run until end of program.

2024-09-04 19:23 UTC, mkolehmainen commented on adapter/ph/src/main.rs
> +            });
Will do.  Not sure why I didn't.

2024-09-04 19:23 UTC, mkolehmainen commented on adapter/ph/src/assembly.rs
> +    pub sa_states: Arc<DashMap<zpr::LinkId, SAState>>,
on it.

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km.rs
> +    pub recv_hmac_key: [u8; 32],
Why not use the same key for both sides?

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km.rs
> +    }
Can just call `Debug::fmt(self, f)` here.

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km.rs
> +    ) -> impl Future<Output = Result<(), mpsc::error::SendError<KMLinkMsg<KMSignal>>>> + 'a {
Often I find these need to be `+ Send` as well to cooperate with Tokio.

Though, you should be able to write this as an `async fn`, no?

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km.rs
> +    pub fn new_empty() -> KMTransportSA {
Maybe implement as `Default::default()`?

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +    table: DashMap<zpr::LinkId, KMHandle<'pktbuf>>, // Not sure how to set the lifetime variable here.
Yes let's move the `KMHandle` into `peer_state` if possible.  Then this structure just becomes the "public interface" to the KM, call it `KmCtl` or some such.

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +pub struct KmState<'pktbuf> {
Consistency nit – here it's `Km` but other places it's `KM`.  I don't have a strong feeling either way (though Rust style seems to lean toward `Km`).

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km.rs
>      statemachine: Box<dyn KeyManagerStateMachine + 'mgr>,
No lifetime annotation is needed here.  `Box<dyn KeyManagerStateMachine>` ensures that the referenced item lives at least as long as this structure and anything that references it.  So I think most/all of the KM structures do not need lifetime parameters.

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +// forever in the Assembly.
See my comment in `km.rs` about lifetime parameters.  I don't think you need any anywhere – default Rust lifetime rules ensure the behavior you want.

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +/// - TODO: This could be more tightly integrated into the assembly.
Yes – this can go into an `RcuBox` in `peer_table`.

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +/// (I've totally copied the pattern that Chris used for other workers but don't really understand it. --mk)
I don't understand it all either! :)  (Wrote it while I was still wrapping my head around Rust-isms and haven't revisited since…)

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +                    _ => {} // TODO: Handle other signals.
There is a `todo!()` macro which panics.

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +        handle.unwrap().1.ctok.cancel(); // stop the KM
It may be best if we also wait on the join handle here (returned by `tokio::spawn()`) so we know the KM has stopped "doing stuff".  (Avoids the class of bugs that a KM worker is stuck in some state continuing to "do stuff" long after we think it's dead.)  That of course would make this an async function but I think that's fine/correct.

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +            }
I feel like this should take down the link somehow, e.g. by sending a signal to the link state machine.

(Some of the KM failure modes include "bad packet" which I think should always immediately bring down a link.)

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +///       the non-blocking call?
Depends where we're calling into this from.  If from the `mgmt_processor` worker, we're already in management land, blocking calls are fine and correct (I don't think we should be shedding load in management land).  But if from the fastpath, then yes, this should be a non-async function and use the `try_handle_km_message` method.  Fastpath must never block.

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +    km_payload: &[u8],
Unless you have a strong objection I think this should be a `Packet`, rather than making a heap allocation and copying the data into it in `handle_km_message()`.  (The caller certainly has no need for the data any longer.)  No need to change in this PR though; I opened a separate task.

Thinking more – I think the interface is _cleaner_ how you have it.  I'm wondering whether there's a way I can make `Packet` implement `Bytes`.  Hm.............

2024-09-04 19:26 UTC, cpacejo commented on adapter/ph/src/km_multiplexor.rs
> +) -> Result<(), String> {
Instead of a `String`, possible to return an enum of some sort here?  That way it can be mapped to a counter type and appropriately counted.

Also I would say that `handle_km_message()` should return a more specific error type than `KMError` – many of the values of `KMError` are things that can only happen while processing the message, whereas only two kinds of errors can occur during enqueueing (queue full, and queue not present).  Best if the caller need only be prepared to handle those cases that actually occur.

(Notably – if we do switch to passing a `Packet` in here, if the enqueue fails, that `Packet` should get passed back so the caller can drop it.  This is how e.g. the `mgmt_processor` queue works.)

2024-09-04 19:28 UTC, cpacejo commented on adapter/ph/src/main.rs
> +            });
I know why, because `main` is a mess right now so it doesn't look out of place :)

2024-09-04 21:28 UTC, cpacejo requested changes
Overall looks good!  Lots of comments mostly nits, some buffer management issues in `fastpath` (hence "request changes").

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +    codec: Arc<dyn Codec>,
Let's pass a `&dyn Codec` here.  (No need for this function to be able to adjust reference counts.)

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +    let encr_len = pkt.body().len() - 1; // Everything except the ZPI byte
`std::mem::size_of::<ZdpZpiHeader>()` is a more verbose way to spell "1" :)

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +    let enc_buf = asm.buffer_stack.try_get_buffer().unwrap();
Just allocate space on the stack here (like you do in the `km` module).  Grabbing and return a buffer is expensive (= mutex lock + unlock for each).  Allocating space on the stack is near zero-cost.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +            error!("encrypt failed: {}", e);
What are the reasons encryption can fail?

Let's not log an error here (logging can block, and if encryption is failing for some state-based reason, we'll flood the log with messages).  Propagate it up a level to `substrate_egress_common()`, and there use `drop_and_count()` to drop `pkt` and count the reason why.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +pub fn encrypt_zero<'pktbuf>(pkt: &mut Packet<'pktbuf>) {
Let's call it `null` instead of `zero` to match the "NULL SA" terminology.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +    codec: Arc<dyn Codec>,
Same comments here re: `&dyn Codec`, 1, and buffers.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +    }
Shouldn't be an error in and of itself I don't think?

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +            error!("decryption failed: {}", e);
Same comment re: logging in the fastpath.  Notably a MitM can trigger this codepath at will.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +/// Process packets ingressing from the specified SA (SocketAddr).
Substrate Address, not SocketAddr.

(Actually the parameter below should be a `&zpr::SubstrateAddr`.  My mistake there.)

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +        }
Stray change from testing?

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +        if zpi_hdr.zpi != 0 {
`zpr::ZPI_0` instead of 0

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +                    );
I think in general we should refrain from logging in the fastpath as it can block.  (Also is an extra point of synchronization, and places pressure on the Icache, etc.)

(more occurrences below)

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +                        sa_state.transport_sa.codec.clone(),
If we pass as a reference (`&*codec`) we can avoid the clone (which entails an atomic operation).

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +            if sa_state.sa_established.load(Ordering::Relaxed) {
Normally I would be a stickler about atomic load/store ordering correctness :) but as discussed earlier this should all be moved into an `RcuBox` inside of `peer_state`.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +        Some(sa_state) => {
If written as `Some(sa_state) if sa_state.sa_established =>`, then both the "unestablished" and "not present" cases can be caught by a single `_ =>` branch, and the NULL decryption handled there.  (Rather than using the `secure` boolean.)

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +    if !secure && base_hdr.packet_type != zdp::ZdpPacketType::KeyManagement {
& if you get rid of `secure` above, here instead of `secure` we can then just check that `zpi == 0`, since we've established by this point that `zpi == 0` if-and-only-if `!secure`.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +                transport_sa = Some(sa_state.transport_sa.clone());
Let's avoid the atomic ref count uptick by passing a reference (`&*sa_state`).

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +                        sa_state.transport_sa.send_zpis.hmac
Near-term future enhancement: hmac vs. encr here should be also controlled by flags in the assembly.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +                    0
Hmm… I would just `drop_and_count()` here.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +            if sa_state.sa_established.load(Ordering::Relaxed) {
`Some(sa_state) if sa_state.sa_established =>` can be used to combine the two "else" cases into one.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +        let tsa = transport_sa.unwrap();
Maybe `match transport_sa { None => encrypt_zero(pkt); Some(tsa) => ... }`

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +                    if zdp_hdr.packet_type == zdp::ZdpPacketType::TransitPacket {
Let's hoist "is it a transit packet?" out of this `match` and perform it first.

2024-09-04 21:28 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +    let decr_buf = asm.buffer_stack.try_get_buffer().unwrap();
(Also -- I think this is missing getting returned to the buffer pool.  But -- switching to a stack allocation avoids the issue entirely.)

2024-09-05 14:14 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +                    );
I understand the desire to log in the fastpath though – and it is possible to do without impacting performance by using a lossy ring buffer – I've opened #386 to look into this

2024-09-05 14:34 UTC, mkolehmainen commented on adapter/ph/src/main.rs
> +            let km_loop_ctok = Box::leak(Box::new(km_mpx_ctok.clone()));
Adding `move` to that opens a whole world of hurt...

2024-09-05 15:21 UTC, mkolehmainen commented on adapter/ph/src/km_multiplexor.rs
> +        handle.unwrap().1.ctok.cancel(); // stop the KM
good call. I forgot that spawn returns something...

2024-09-05 16:24 UTC, cpacejo commented on adapter/ph/src/main.rs
> +            let km_loop_ctok = Box::leak(Box::new(km_mpx_ctok.clone()));
Oh because then it tries to copy/move `asm`.  This issue is addressed by the structure of the `launch()` functions I write for workers (all of which use `async move`).  If you do the same for this worker it should be trivial to pass in `km_mpx_ctok.clone()` as an argument which then gets moved into the worker.

2024-09-05 16:32 UTC, cpacejo commented on adapter/ph/src/peer_table.rs
> +    link_to_sec_assoc: DashMap<LinkId, SAState>,
Sorry what I meant more specifically is – `SAState` can/should move into `PeerState` here -- `peer_slab` is where the actual contents of the peer table live.  (`peer_slab_reader` is just a read-only handle, and `sa_to_link` is just a reverse mapping.)

I recognize this is probably a headache to do so feel free to address in a separate commit / or I can take a stab at it as I know the Rcu and Cslab stuff more intimately.

2024-09-05 17:13 UTC, mkolehmainen commented on adapter/ph/src/fastpath.rs
> +/// Process packets ingressing from the specified SA (SocketAddr).
Yes, I got well into this before I realized that you were not using "sa" to mean "Security Association".  I am removing all instances of "sa" meaning "security assocaition" now.

2024-09-05 19:08 UTC, mkolehmainen commented on adapter/ph/src/fastpath.rs
> +            if sa_state.sa_established.load(Ordering::Relaxed) {
This I don't understand!

2024-09-05 19:24 UTC, mkolehmainen commented on adapter/ph/src/peer_table.rs
> +    link_to_sec_assoc: DashMap<LinkId, SAState>,
Ah! Yes, let me make another task for that.  At same time can iron out the use of clone and reference which is also causing me issues.

2024-09-05 19:27 UTC, cpacejo commented on adapter/ph/src/km_noise.rs
> +                    "noise failed to encrypt message: {}",
I think in this case it's OK to panic – I think the only cases that encryption can fail other than `Error::Input` is due to a logic/setup error on our part, in which case it's not possible to continue in any way.

2024-09-05 19:27 UTC, cpacejo commented on adapter/ph/src/km_noise.rs
> +                snow::error::Error::Input => Err(EncryptionError::MessageTooLarge),
It looks like this can [only be generated](https://docs.rs/snow/latest/src/snow/stateless_transportstate.rs.html#64-65) if either the output buffer is too small (which we should be able to statically ensure it's not) or the overall message is > 64 KiB (which we should also be able to ensure doesn't happen).  I wish `snow` exposed these constants but they are found [here](https://docs.rs/snow/latest/src/snow/constants.rs.html#8).

What I'm aiming for is encryption should never fail "dynamically", with the exception that we've encrypted too many bytes and therefore need to / should have already performed a rekey.  Simply because there's nothing really useful we can do to respond to a dynamic failure other than drop the packet, which doesn't help the sending application figure out why its packets aren't going through and adjust its behavior.

Not worth solving now I don't think but maybe worth a note.

2024-09-05 19:27 UTC, cpacejo commented on adapter/ph/src/km_noise.rs
> +        let nonce: u64 = u64::from_be_bytes(payload[0..NOISE_NONCE_LEN].try_into().unwrap()); // pretty sure this cannot fail
Alternative: the `array_ref![]` macro: https://docs.rs/arrayref/latest/arrayref/macro.array_ref.html  which allows slicing an array to another array.  (This is fine/correct as-is though.)

2024-09-05 19:30 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +    // TODO: Is there some way to avoid a clone here?
If the SA stuff lives inside a `peer_table` entry then you can just `inspect()` the entry and will have access to whatever's in there for the duration of the call to `inspect()`.

2024-09-05 19:39 UTC, cpacejo commented on adapter/ph/src/fastpath.rs
> +            if sa_state.sa_established.load(Ordering::Relaxed) {
The `if xxx` is termed a "guard".  What it means is – the match scrutinee (the expression after `match`) is first matched against the match arm's pattern (`Some(sa_state)` in this case).  If it matches, the variables are bound (`sa_state` here), and then the arm's guard expression is checked.  If it's true, the match arm's block is then executed.  If the guard expression is false, the arm is considered not to match, and the next pattern is checked.  So instead of writing:

```
match foo {
  Some(x) => {
    if x > 5 { do stuff when x > 5 }
    else { do stuff when x <= 5 }
  }
  None => { do stuff when there's no x }
}
```
you can write:
```
match foo {
  Some(x) if x > 5 => { do stuff when x > 5 }
  Some(x) => { do stuff when x <= 5 }
  None => { do stuff when there's no x }
}
```
Or, if you want to do the same stuff when `x <= 5` or there is no `x`:
```
match foo {
  Some(x) when x > 5 => { do stuff when x > 5 }
  Some(_) | None => { do stuff when x <= 5 or there's no x }
}
```
or you can save characters at the expense of fewer static checks like so:
```
match foo {
  Some(x) if x > 5 => { do stuff when x > 5 }
  _ => { do stuff when x <= 5 or there's no x }
}
```

Not a code issue here, I think it's fine to be checked in as-is.  Just an easier way to express what's written in my opinion.

2024-09-05 19:44 UTC, mkolehmainen commented on adapter/ph/src/main.rs
> +            let km_loop_ctok = Box::leak(Box::new(km_mpx_ctok.clone()));
Yes, this is moved into a worker now.

2024-09-05 19:45 UTC, mkolehmainen commented on adapter/ph/src/km.rs
> +    pub recv_hmac_key: [u8; 32],
I don't know... I just copied how I was exchanging the ZPIs.

2024-09-05 19:46 UTC, mkolehmainen commented on adapter/ph/src/fastpath.rs
> +            if sa_state.sa_established.load(Ordering::Relaxed) {
thanks for explanation!

2024-09-05 19:56 UTC, mkolehmainen commented on adapter/ph/src/km_noise.rs
> +                    "noise failed to encrypt message: {}",
ok!

2024-09-05 20:07 UTC, cpacejo approved these changes
Thanks for making all these changes!  I think everything major is taken care of… like I mentioned feel free to leave the `peer_state` stuff for me to sort out.

2024-09-06 14:59 UTC, mkolehmainen commented on adapter/ph/src/km.rs
>      statemachine: Box<dyn KeyManagerStateMachine + 'mgr>,
phew

2024-09-06 15:08 UTC, mkolehmainen commented on adapter/ph/src/km_multiplexor.rs
> +            }
Yes.  I think so. We need to centralize the link-setup procedure.  When we create a link in the peer-table there are things that should happen, including starting up KM.  There are many things that can bring a link down (eg, KM completely fails after too many retries, or user kills it, or visa service/admin kills it, or it is lost based on some other retry mechanism like keep alives go missing...).  I'll add a task but it is pretty vague at the moment.

2024-09-06 15:16 UTC, merged