remove protocol buffer visa from thrift apis
org-zpr/zpr-core pull request #427
Opened 2024-09-13 21:49 UTC by mkolehmainen

Protocol buffer still used internall by visaservice and by the zplc (which isn't even part of ref impl yet). But at the interface now converts to a thrift version of the visa datastructure.

To make things easier, I also moved all the thrift files into a single source file (vs.thrift).

2024-09-19 15:02 UTC, svjaffer requested changes
Sorry, Mathias, but I can't review this, though I did try.

Having code that is generated and doesn't need to be reviewed intermingled with code that was written and does need to be reviewed places a burden on the reviewer to tell them apart, especially in a review this overwhelmingly large.

The comments of a PR is probably not an appropriate place to have this discussion, but I think it's a bad idea to check in generated code in the first place, partly for this reason.  But if we're going to continue doing this, a suggestion: break apart the generated code from the non-generated code, either in separate PRs or clearly delineated commits.  That makes it visually clear what needs to be reviewed and what can just be rubber-stamped.

2024-09-19 16:51 UTC, mkolehmainen commented
Ok, I'll try adding some comments in here to see if that makes things clearer...

2024-09-19 16:52 UTC, mkolehmainen commented on node/src/vsapi/mod.rs
AUTO GENERATED!!

2024-09-19 16:53 UTC, mkolehmainen commented on visaservice/cli/src/vsapi/mod.rs
AUTO GENERATED!!

2024-09-19 16:54 UTC, mkolehmainen commented on visaservice/core/pkg/libvisa/transcode.go
This is the significant part of this whole PR.  In which a native visa struct is converted to a thrift one for public consumption.

2024-09-19 16:54 UTC, mkolehmainen commented on visaservice/core/pkg/vsapi/vs.go
AUTO GENERATED!!

2024-09-19 16:56 UTC, mkolehmainen commented on visaservice/thrift/vs.thrift
The other work for the PR is in here, where I just created a VISA struct in thrift based on the prototype one.

I also combined all the separate thrift files into one because using multiple ones was causing issues which made the sharing of types difficult.

2024-09-19 20:15 UTC, svjaffer commented on visaservice/core/pkg/libvisa/transcode.go
> +	"google.golang.org/protobuf/proto"
Is this protobuf import just leftover code?

2024-09-19 20:19 UTC, svjaffer commented on visaservice/thrift/vs.thrift
> +//     ~~ Now this visa sercice API kicks in ~~
Just a typo: sercice => service

2024-09-23 17:28 UTC, mkolehmainen commented on visaservice/core/pkg/libvisa/transcode.go
> +	"google.golang.org/protobuf/proto"
There is still protocol buffer stuff in the visaservice.  For example, the policy (output from the zpl compiler) is contained in a protobuf structure.  The visa service itself still creates protocol buffer visas which are then converted to thrift visas as they leave through the thrift API.

2024-09-23 18:11 UTC, svjaffer approved these changes

2024-09-23 18:46 UTC, merged