Link State 2: The State Machine
org-zpr/zpr-core pull request #504
Opened 2024-10-29 18:59 UTC by svjaffer

This commit introduces most of the link state machine internals and hooks up the events that make it run.  Handshakes now proceed in order as expected and some hacks have been removed.

Some of the other random stuff in here is about getting Register Agent Address to work as part of the bringup process.

2024-10-30 15:54 UTC, cpacejo reviewed
Reviewed all except the changes to `link_state` so far!

2024-10-30 15:54 UTC, cpacejo commented on adapter/ph/src/assembly.rs
>      }
If this is unused I'd just as soon delete it!

2024-10-30 15:54 UTC, cpacejo commented on adapter/ph/src/assembly.rs
> +                || peer_state.link_state_machine.start(self).is_err()
Can we capture what these errors are and include them in the error message?

2024-10-30 15:54 UTC, cpacejo commented on adapter/ph/src/assembly.rs
> +        self.peer_table.inspect(peer_id, |peer_state| {
Using `.get()` here instead of `.inspect()` might make the code flow a bit more smoothly.  (Also will make explicit handling of the case that peer state got deleted somehow.)

2024-10-30 15:54 UTC, cpacejo commented on adapter/ph/src/peer_table.rs
> +        let _ = entry.link_state_machine.keying_done(asm);
Do we know here this method can never return an error?

2024-10-30 15:54 UTC, cpacejo commented on adapter/ph/src/mgmt/handlers.rs
> +    }) {
Alternative less nesty way to write this:

```
let Some(Ok(_)) = inspect(..) else { return Err(...) };
let mut rsp_pkt = ...
...
Ok(())
```

2024-10-30 17:08 UTC, svjaffer commented on adapter/ph/src/peer_table.rs
> +        let _ = entry.link_state_machine.keying_done(asm);
Oh, I just missed this spot when adding the result handling.  I'll fix that!

2024-10-30 17:08 UTC, svjaffer commented on adapter/ph/src/assembly.rs
>      }
Done

2024-10-30 17:12 UTC, svjaffer commented on adapter/ph/src/mgmt/handlers.rs
> +    }) {
Done

2024-10-30 18:08 UTC, cpacejo requested changes
Nice I like it!!

Only major change I think we should make though is making the state transitions atomic.

2024-10-30 18:08 UTC, cpacejo commented on adapter/ph/src/link_state.rs
> +pub enum LinkStateError {
For errors ideally they `#[derive(Debug)]` and also `impl Display` and `impl std::error::Error`.  Mathias though found this crate `thiserror` and added a dependency on it, which automates the process of implementing the latter two traits: https://docs.rs/thiserror/latest/thiserror/

2024-10-30 18:08 UTC, cpacejo commented on adapter/ph/src/link_state.rs
> +    pub fn set_silent(&mut self) {
No need for `mut` here

2024-10-30 18:08 UTC, cpacejo commented on adapter/ph/src/link_state.rs
> +        assert!(self.id != 0);
0 -> `zpr::LINK_ID_UNKNOWN`

2024-10-30 18:08 UTC, cpacejo commented on adapter/ph/src/link_state.rs
> +        self.set_state(LinkState::Keying);
Here and elsewhere we do a lot of taking and dropping the lock, making this method not have a definite linearization point (and opens the potential for race conditions under concurrent access).  If the bodies of these methods were all implemented on `LinkStateMachine` directly, and then these methods just took the lock and forwarded to `LinkStateMachine`, they'd all have a linearization point and avoid race conditions.

2024-10-30 18:08 UTC, cpacejo commented on adapter/ph/src/mgmt/requests.rs
> +            }
Can you add a TODO here that this is temporary until we break apart the async sync request stuff?  (Want to make sure we don't forget, as in the `async` design as-is, calling directly back specifically to the link state machine breaks the return-to-caller model.)

2024-10-30 18:08 UTC, cpacejo commented on adapter/ph/src/link_state.rs
> +    fn send_hello<'pktbuf>(&self, asm: &'static Assembly<'pktbuf>) {
Maybe name `maybe_send_hello()` since this only actually does that conditionally?

2024-10-30 18:08 UTC, cpacejo commented on adapter/ph/src/link_state.rs
> +            }
Should we return an error here like above?

2024-10-30 18:08 UTC, cpacejo commented on adapter/ph/src/link_state.rs
> +                self.run_active(asm)
Just marking here an example of a sequence that I think ought all to be performed under a single lock, so the transition is atomic.

2024-10-30 18:08 UTC, cpacejo commented on adapter/ph/src/link_state.rs
> +        self.set_state(LinkState::Closing);
Will stuff be happening in here in a later commit?

Also -- I think here we should bring the TUN carrier down?

2024-10-30 18:08 UTC, cpacejo commented on adapter/ph/src/link_state.rs
> +    pub fn reset(&self) {
Is `reset()` a state transition or is it "special" (a reset of the data structure)?  If it's a state transition, how does it differ from `shutdown()`?

Either case here I think we should bring the TUN carrier down?

2024-10-30 18:17 UTC, svjaffer commented on adapter/ph/src/link_state.rs
> +    pub fn set_silent(&mut self) {
Done

2024-10-30 18:17 UTC, svjaffer commented on adapter/ph/src/link_state.rs
> +        assert!(self.id != 0);
Done

2024-10-30 18:17 UTC, svjaffer commented on adapter/ph/src/link_state.rs
> +        self.set_state(LinkState::Keying);
Done

2024-10-30 18:18 UTC, svjaffer commented on adapter/ph/src/link_state.rs
> +    fn send_hello<'pktbuf>(&self, asm: &'static Assembly<'pktbuf>) {
Sure, done

2024-10-30 18:19 UTC, svjaffer commented on adapter/ph/src/link_state.rs
> +        self.set_state(LinkState::Closing);
Yes, I'm missing some TODOs here.  Link shutdown isn't called currently, but I'll be fleshing this operation out in a subsequent commit.

2024-10-30 18:20 UTC, svjaffer commented on adapter/ph/src/link_state.rs
> +    pub fn reset(&self) {
Reset and close have different behavior in how they bring the link down, but yes, the tun carrier should come down.

2024-10-30 18:30 UTC, svjaffer commented on adapter/ph/src/link_state.rs
> +            }
Yes, fixed

2024-10-30 18:31 UTC, svjaffer commented on adapter/ph/src/mgmt/requests.rs
> +            }
Done

2024-10-30 18:48 UTC, svjaffer commented on adapter/ph/src/link_state.rs
> +pub enum LinkStateError {
Nice!

2024-10-31 14:48 UTC, cpacejo approved these changes
Looks good go go go!

2024-10-31 14:52 UTC, merged