ability to build on mac, run an adapter
org-zpr/zpr-core pull request #507
Opened 2024-10-31 13:55 UTC by mkolehmainen

Permits compiling on a mac, and you can bring up an adapter and successfully connect to a node on linux.

There is still some work to do around the TUN interface.  This simply brings up an interface and sets an address (and mtu).  But we still need to add the correct routing.  

I'll make a story for that and for the "set MTU" thing for the UdpSocket stuff in zpr-ext.

2024-11-04 16:51 UTC, cpacejo requested changes
Looks good!  Just a couple minor suggestions to change

2024-11-04 16:51 UTC, cpacejo commented on adapter/ph/Cargo.toml
> +tun = { version = "=0.7.1", features = ["async"] }
0.6.1 is the last "unadulterated" version.

Aside -- because we'll be open-source (as will our commit history), I'd reword the comment to be in neutral terms.  E.g. "Locked version, because rust-tun 0.7 was substantially reworked by a new maintainer, removing several features we depend on."

2024-11-04 16:51 UTC, cpacejo commented on zpr-ext/src/tokio.rs
> +    #[cfg(target_os = "linux")]
Both `linux` and `android` here to match the use sites below.

(For context I've been specifying both of those to match what I've seen in some other libraries.  Since Android essential "is" Linux.)

2024-11-04 16:51 UTC, cpacejo commented on zpr-ext/src/std.rs
> +    #[cfg(unix)]
`cfg(any(doc, unix))` ensures this shows up in documentation also.  (Which I believe gets built without any "target" options set.)

2024-11-04 16:51 UTC, cpacejo commented on zpr-ext/src/std.rs
> +            #[cfg(any(target_os = "android", target_os = "linux"))]
And then also here add `doc` (but not to the "macos" variant).

2024-11-04 16:51 UTC, cpacejo commented on adapter/ph/src/sys/macos/zprtun.rs
> +        idev.send(_buf)
`buf` instead of `_buf` since it's used now :)

2024-11-05 19:02 UTC, mkolehmainen commented on adapter/ph/Cargo.toml
> +tun = { version = "=0.7.1", features = ["async"] }
Noted.  Altered comment, but keeping at 0.7.1 since that one works for us for now.

2024-11-05 19:07 UTC, mkolehmainen commented on adapter/ph/src/sys/macos/zprtun.rs
> +        idev.send(_buf)
oh good catch!

2024-11-05 20:22 UTC, cpacejo commented on adapter/ph/Cargo.toml
> +tun = { version = "=0.7.1", features = ["async"] }
I'm OK to check this in with 0.7.1 for just macOS but I do want to unify across OSes and we can't do that with 0.7.1.  0.6.1 is the last version that supports multiqueue and vectored I/O.

2024-11-05 20:25 UTC, cpacejo approved these changes
Looks good thanks!

2024-11-05 20:39 UTC, merged